use crate::schema::nba::schedule::{NBAQuarter, NBAScheduleGame};
use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct NBATeamGame {
    #[serde(rename = "StatID")]
    pub stat_id: i64,
    #[serde(rename = "TeamID")]
    pub team_id: i32,
    #[serde(rename = "SeasonType")]
    pub season_type: i32,
    #[serde(rename = "Season")]
    pub season: i32,
    #[serde(rename = "Name")]
    pub name: String,
    #[serde(rename = "Team")]
    pub team: String,
    #[serde(rename = "Wins")]
    pub wins: i32,
    #[serde(rename = "Losses")]
    pub losses: i32,
    #[serde(rename = "Possessions")]
    pub possessions: f64,
    #[serde(rename = "GlobalTeamID")]
    pub global_team_id: i64,
    #[serde(rename = "GameID")]
    pub game_id: i64,
    #[serde(rename = "OpponentID")]
    pub opponent_id: i32,
    #[serde(rename = "Opponent")]
    pub opponent: String,
    #[serde(rename = "Day")]
    pub day: String,
    #[serde(rename = "DateTime")]
    pub date_time: String,
    #[serde(rename = "HomeOrAway")]
    pub home_or_away: String,
    #[serde(rename = "IsGameOver")]
    pub is_game_over: bool,
    #[serde(rename = "GlobalGameID")]
    pub global_game_id: i64,
    #[serde(rename = "GlobalOpponentID")]
    pub global_opponent_id: i64,
    #[serde(rename = "Updated")]
    pub updated: String,
    #[serde(rename = "Games")]
    pub games: i32,
    #[serde(rename = "FantasyPoints")]
    pub fantasy_points: f64,
    #[serde(rename = "Minutes")]
    pub minutes: i32,
    #[serde(rename = "Seconds")]
    pub seconds: i32,
    #[serde(rename = "FieldGoalsMade")]
    pub field_goals_made: f64,
    #[serde(rename = "FieldGoalsAttempted")]
    pub field_goals_attempted: i32,
    #[serde(rename = "FieldGoalsPercentage")]
    pub field_goals_percentage: f64,
    #[serde(rename = "EffectiveFieldGoalsPercentage")]
    pub effective_field_goals_percentage: f64,
    #[serde(rename = "TwoPointersMade")]
    pub two_pointers_made: f64,
    #[serde(rename = "TwoPointersAttempted")]
    pub two_pointers_attempted: f64,
    #[serde(rename = "TwoPointersPercentage")]
    pub two_pointers_percentage: f64,
    #[serde(rename = "ThreePointersMade")]
    pub three_pointers_made: f64,
    #[serde(rename = "ThreePointersAttempted")]
    pub three_pointers_attempted: f64,
    #[serde(rename = "ThreePointersPercentage")]
    pub three_pointers_percentage: f64,
    #[serde(rename = "FreeThrowsMade")]
    pub free_throws_made: f64,
    #[serde(rename = "FreeThrowsAttempted")]
    pub free_throws_attempted: f64,
    #[serde(rename = "FreeThrowsPercentage")]
    pub free_throws_percentage: f64,
    #[serde(rename = "OffensiveRebounds")]
    pub offensive_rebounds: f64,
    #[serde(rename = "DefensiveRebounds")]
    pub defensive_rebounds: f64,
    #[serde(rename = "Rebounds")]
    pub rebounds: f64,
    #[serde(rename = "OffensiveReboundsPercentage")]
    pub offensive_rebounds_percentage: Option<f64>,
    #[serde(rename = "DefensiveReboundsPercentage")]
    pub defensive_rebounds_percentage: Option<f64>,
    #[serde(rename = "TotalReboundsPercentage")]
    pub total_rebounds_percentage: Option<f64>,
    #[serde(rename = "Assists")]
    pub assists: f64,
    #[serde(rename = "Steals")]
    pub steals: f64,
    #[serde(rename = "BlockedShots")]
    pub blocked_shots: f64,
    #[serde(rename = "Turnovers")]
    pub turnovers: f64,
    #[serde(rename = "PersonalFouls")]
    pub personal_fouls: f64,
    #[serde(rename = "Points")]
    pub points: f64,
    #[serde(rename = "TrueShootingAttempts")]
    pub true_shooting_attempts: f64,
    #[serde(rename = "TrueShootingPercentage")]
    pub true_shooting_percentage: f64,
    #[serde(rename = "PlayerEfficiencyRating")]
    pub player_efficiency_rating: Option<f64>,
    #[serde(rename = "AssistsPercentage")]
    pub assists_percentage: Option<f64>,
    #[serde(rename = "StealsPercentage")]
    pub steals_percentage: Option<f64>,
    #[serde(rename = "BlocksPercentage")]
    pub blocks_percentage: Option<f64>,
    #[serde(rename = "TurnOversPercentage")]
    pub turn_overs_percentage: Option<f64>,
    #[serde(rename = "UsageRatePercentage")]
    pub usage_rate_percentage: Option<f64>,
    #[serde(rename = "FantasyPointsFanDuel")]
    pub fantasy_points_fan_duel: f64,
    #[serde(rename = "FantasyPointsDraftKings")]
    pub fantasy_points_draft_kings: f64,
    #[serde(rename = "FantasyPointsYahoo")]
    pub fantasy_points_yahoo: f64,
    #[serde(rename = "PlusMinus")]
    pub plus_minus: f64,
    #[serde(rename = "DoubleDoubles")]
    pub double_doubles: i32,
    #[serde(rename = "TripleDoubles")]
    pub triple_doubles: i32,
    #[serde(rename = "FantasyPointsFantasyDraft")]
    pub fantasy_points_fantasy_draft: f64,
    #[serde(rename = "IsClosed")]
    pub is_closed: bool,
    #[serde(rename = "LineupConfirmed")]
    pub lineup_confirmed: Option<bool>,
    #[serde(rename = "LineupStatus")]
    pub lineup_status: String,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct NBAPlayerGame {
    #[serde(rename = "StatID")]
    pub stat_id: i64,
    #[serde(rename = "TeamID")]
    pub team_id: i32,
    #[serde(rename = "PlayerID")]
    pub player_id: i64,
    #[serde(rename = "SeasonType")]
    pub season_type: i32,
    #[serde(rename = "Season")]
    pub season: i32,
    #[serde(rename = "Name")]
    pub name: String,
    #[serde(rename = "Team")]
    pub team: String,
    #[serde(rename = "Position")]
    pub position: String,
    #[serde(rename = "Started")]
    pub started: i32,
    #[serde(rename = "FanDuelSalary")]
    pub fan_duel_salary: Option<i32>,
    #[serde(rename = "DraftKingsSalary")]
    pub draft_kings_salary: Option<i32>,
    #[serde(rename = "FantasyDataSalary")]
    pub fantasy_data_salary: Option<i32>,
    #[serde(rename = "YahooSalary")]
    pub yahoo_salary: Option<i32>,
    #[serde(rename = "InjuryStatus")]
    pub injury_status: String,
    #[serde(rename = "InjuryBodyPart")]
    pub injury_body_part: String,
    #[serde(rename = "InjuryStartDate")]
    pub injury_start_date: Option<String>,
    #[serde(rename = "InjuryNotes")]
    pub injury_notes: String,
    #[serde(rename = "FanDuelPosition")]
    pub fan_duel_position: Option<String>,
    #[serde(rename = "DraftKingsPosition")]
    pub draft_kings_position: Option<String>,
    #[serde(rename = "YahooPosition")]
    pub yahoo_position: Option<String>,
    #[serde(rename = "OpponentRank")]
    pub opponent_rank: i32,
    #[serde(rename = "OpponentPositionRank")]
    pub opponent_position_rank: i32,
    #[serde(rename = "GlobalTeamID")]
    pub global_team_id: i64,
    #[serde(rename = "FantasyDraftSalary")]
    pub fantasy_draft_salary: Option<i32>,
    #[serde(rename = "FantasyDraftPosition")]
    pub fantasy_draft_position: Option<String>,
    #[serde(rename = "GameID")]
    pub game_id: i64,
    #[serde(rename = "OpponentID")]
    pub opponent_id: i32,
    #[serde(rename = "Opponent")]
    pub opponent: String,
    #[serde(rename = "Day")]
    pub day: String,
    #[serde(rename = "DateTime")]
    pub date_time: String,
    #[serde(rename = "HomeOrAway")]
    pub home_or_away: String,
    #[serde(rename = "IsGameOver")]
    pub is_game_over: bool,
    #[serde(rename = "GlobalGameID")]
    pub global_game_id: i64,
    #[serde(rename = "GlobalOpponentID")]
    pub global_opponent_id: i64,
    #[serde(rename = "Updated")]
    pub updated: String,
    #[serde(rename = "Games")]
    pub games: i32,
    #[serde(rename = "FantasyPoints")]
    pub fantasy_points: f64,
    #[serde(rename = "Minutes")]
    pub minutes: i32,
    #[serde(rename = "Seconds")]
    pub seconds: i32,
    #[serde(rename = "FieldGoalsMade")]
    pub field_goals_made: f64,
    #[serde(rename = "FieldGoalsAttempted")]
    pub field_goals_attempted: f64,
    #[serde(rename = "FieldGoalsPercentage")]
    pub field_goals_percentage: f64,
    #[serde(rename = "EffectiveFieldGoalsPercentage")]
    pub effective_field_goals_percentage: f64,
    #[serde(rename = "TwoPointersMade")]
    pub two_pointers_made: f64,
    #[serde(rename = "TwoPointersAttempted")]
    pub two_pointers_attempted: f64,
    #[serde(rename = "TwoPointersPercentage")]
    pub two_pointers_percentage: f64,
    #[serde(rename = "ThreePointersMade")]
    pub three_pointers_made: f64,
    #[serde(rename = "ThreePointersAttempted")]
    pub three_pointers_attempted: f64,
    #[serde(rename = "ThreePointersPercentage")]
    pub three_pointers_percentage: f64,
    #[serde(rename = "FreeThrowsMade")]
    pub free_throws_made: f64,
    #[serde(rename = "FreeThrowsAttempted")]
    pub free_throws_attempted: f64,
    #[serde(rename = "FreeThrowsPercentage")]
    pub free_throws_percentage: f64,
    #[serde(rename = "OffensiveRebounds")]
    pub offensive_rebounds: f64,
    #[serde(rename = "DefensiveRebounds")]
    pub defensive_rebounds: f64,
    #[serde(rename = "Rebounds")]
    pub rebounds: f64,
    #[serde(rename = "OffensiveReboundsPercentage")]
    pub offensive_rebounds_percentage: f64,
    #[serde(rename = "DefensiveReboundsPercentage")]
    pub defensive_rebounds_percentage: f64,
    #[serde(rename = "TotalReboundsPercentage")]
    pub total_rebounds_percentage: f64,
    #[serde(rename = "Assists")]
    pub assists: f64,
    #[serde(rename = "Steals")]
    pub steals: f64,
    #[serde(rename = "BlockedShots")]
    pub blocked_shots: f64,
    #[serde(rename = "Turnovers")]
    pub turnovers: f64,
    #[serde(rename = "PersonalFouls")]
    pub personal_fouls: f64,
    #[serde(rename = "Points")]
    pub points: f64,
    #[serde(rename = "TrueShootingAttempts")]
    pub true_shooting_attempts: f64,
    #[serde(rename = "TrueShootingPercentage")]
    pub true_shooting_percentage: f64,
    #[serde(rename = "PlayerEfficiencyRating")]
    pub player_efficiency_rating: f64,
    #[serde(rename = "AssistsPercentage")]
    pub assists_percentage: f64,
    #[serde(rename = "StealsPercentage")]
    pub steals_percentage: f64,
    #[serde(rename = "BlocksPercentage")]
    pub blocks_percentage: f64,
    #[serde(rename = "TurnOversPercentage")]
    pub turn_overs_percentage: f64,
    #[serde(rename = "UsageRatePercentage")]
    pub usage_rate_percentage: f64,
    #[serde(rename = "FantasyPointsFanDuel")]
    pub fantasy_points_fan_duel: f64,
    #[serde(rename = "FantasyPointsDraftKings")]
    pub fantasy_points_draft_kings: f64,
    #[serde(rename = "FantasyPointsYahoo")]
    pub fantasy_points_yahoo: f64,
    #[serde(rename = "PlusMinus")]
    pub plus_minus: f64,
    #[serde(rename = "DoubleDoubles")]
    pub double_doubles: i32,
    #[serde(rename = "TripleDoubles")]
    pub triple_doubles: i32,
    #[serde(rename = "FantasyPointsFantasyDraft")]
    pub fantasy_points_fantasy_draft: f64,
    #[serde(rename = "IsClosed")]
    pub is_closed: bool,
    #[serde(rename = "LineupConfirmed")]
    pub lineup_confirmed: bool,
    #[serde(rename = "LineupStatus")]
    pub lineup_status: String,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct NBABoxScoreResponse {
    #[serde(rename = "Game")]
    pub game: NBAScheduleGame,
    #[serde(rename = "Quarters")]
    pub quarters: Vec<NBAQuarter>,
    #[serde(rename = "TeamGames")]
    pub team_games: Vec<NBATeamGame>,
    #[serde(rename = "PlayerGames")]
    pub player_games: Vec<NBAPlayerGame>,
}
