# Arbitration API Server Configuration

[server]
host = "0.0.0.0"
port = 3000
cors_origins = "http://localhost:5173,http://localhost:3000"

[cache]
enabled = true
redis_url = "redis://localhost:6379"
default_ttl = 3600

[cache.ttl]
team_profiles = 3600      # 1 hour
schedule = 1800           # 30 minutes
postseason_schedule = 1800 # 30 minutes
scores = 120              # 2 minutes
play_by_play = 20         # 20 seconds
box_scores = 1800         # 30 minutes
stadiums = 7200           # 2 hours
twitter_search = 60       # 1 minute

[seasons.current_seasons.mlb]
regular = "2025"
postseason = "2025POST"
postseason_start = "10-01"

[seasons.current_seasons.nfl]
regular = "2025"
postseason = "2025POST"
postseason_start = "01-01"

[seasons.current_seasons.nba]
regular = "2025"
postseason = "2025POST"
postseason_start = "04-01"

[seasons.current_seasons.nhl]
regular = "2025"
postseason = "2025POST"
postseason_start = "04-01"

[api]
sportsdata_base_url = "https://api.sportsdata.io/v3"
twitter_base_url = "https://api.twitterapi.io"
request_timeout = 30
