# Arbitration API Server Configuration

[server]
host = "0.0.0.0"
port = 3000
cors_origins = "http://localhost:5173,http://localhost:3000,https://eaa2da739953.ngrok.app"
client_url = "https://eaa2da739953.ngrok.app"

[cache]
enabled = true
mode = "TtlBased"
redis_url = "redis://localhost:6379"
default_ttl = 60

[cache.ttl]
team_profiles = 3600      # 1 hour
schedule = 3600           # 1 hour
postseason_schedule = 3600 # 1 hour
scores = 60               # 1 minute
play_by_play = 60         # 1 minute
box_scores = 60           # 1 minute
stadiums = 21600          # 6 hours
twitter_search = 60       # 1 minute
reddit_thread = 600       # 10 minutes
reddit_thread_comments = 60 # 1 minute
odds = 3600               # 1 hour
user_auth = 604800        # 1 week (7 days)

[seasons.current_seasons.mlb]
regular = "2025"
postseason = "2025POST"
postseason_start = "10-01"

[seasons.current_seasons.nfl]
regular = "2025"
postseason = "2025POST"
postseason_start = "01-01"

[seasons.current_seasons.nba]
regular = "2025"
postseason = "2025POST"
postseason_start = "04-01"

[seasons.current_seasons.nhl]
regular = "2025"
postseason = "2025POST"
postseason_start = "04-01"

[api]
sportsdata_base_url = "https://api.sportsdata.io/v3"
twitter_base_url = "https://api.twitterapi.io"
request_timeout = 30

[api.reddit_api]
default_comment_limit = 20
max_comment_limit = 100
default_sort = "new"
user_agent = "arbitration-app/1.0 by u/arbitration_dev"
