import Fuse from "fuse.js";
import { League } from "./config";

export interface Team {
  id: string;
  name: string;
  league: string;
  leagueColor: string;
  city?: string;
  subreddit?: string;
  abbreviation?: string;
}

// Helper function to generate team ID in format: league--city-team
const generateTeamId = (league: string, city: string, teamName: string): string => {
  const leagueLower = league.toLowerCase();
  const cityShort = city.toLowerCase().replace(/\s+/g, '');
  const teamShort = teamName.toLowerCase().replace(/\s+/g, '-');
  return `${leagueLower}--${cityShort}-${teamShort}`;
};

export const allTeams: Team[] = [
  // NFL Teams (32 teams)
  {
    id: generateTeamId("NFL", "Arizona", "cardinals"),
    name: "Arizona Cardinals",
    league: "NFL",
    leagueColor: "#97233F",
    city: "Arizona",
    subreddit: "r/AZCardinals",
    abbreviation: "ARI",
  },
  {
    id: generateTeamId("NFL", "Atlanta", "falcons"),
    name: "Atlanta Falcons",
    league: "NFL",
    leagueColor: "#A71930",
    city: "Atlanta",
    subreddit: "r/falcons",
    abbreviation: "ATL",
  },
  {
    id: generateTeamId("NFL", "Baltimore", "ravens"),
    name: "Baltimore Ravens",
    league: "NFL",
    leagueColor: "#241773",
    city: "Baltimore",
    subreddit: "r/ravens",
    abbreviation: "BAL",
  },
  {
    id: generateTeamId("NFL", "Buffalo", "bills"),
    name: "Buffalo Bills",
    league: "NFL",
    leagueColor: "#00338D",
    city: "Buffalo",
    subreddit: "r/buffalobills",
    abbreviation: "BUF",
  },
  {
    id: generateTeamId("NFL", "Carolina", "panthers"),
    name: "Carolina Panthers",
    league: "NFL",
    leagueColor: "#0085CA",
    city: "Carolina",
    subreddit: "r/panthers",
    abbreviation: "CAR",
  },
  {
    id: generateTeamId("NFL", "Chicago", "bears"),
    name: "Chicago Bears",
    league: "NFL",
    leagueColor: "#0B162A",
    city: "Chicago",
    subreddit: "r/chibears",
    abbreviation: "CHI",
  },
  {
    id: generateTeamId("NFL", "Cincinnati", "bengals"),
    name: "Cincinnati Bengals",
    league: "NFL",
    leagueColor: "#FB4F14",
    city: "Cincinnati",
    subreddit: "r/bengals",
    abbreviation: "CIN",
  },
  {
    id: generateTeamId("NFL", "Cleveland", "browns"),
    name: "Cleveland Browns",
    league: "NFL",
    leagueColor: "#311D00",
    city: "Cleveland",
    subreddit: "r/browns",
    abbreviation: "CLE",
  },
  {
    id: generateTeamId("NFL", "Dallas", "cowboys"),
    name: "Dallas Cowboys",
    league: "NFL",
    leagueColor: "#003594",
    city: "Dallas",
    subreddit: "r/cowboys",
    abbreviation: "DAL",
  },
  {
    id: generateTeamId("NFL", "Denver", "broncos"),
    name: "Denver Broncos",
    league: "NFL",
    leagueColor: "#FB4F14",
    city: "Denver",
    subreddit: "r/denverbroncos",
    abbreviation: "DEN",
  },
  {
    id: generateTeamId("NFL", "Detroit", "lions"),
    name: "Detroit Lions",
    league: "NFL",
    leagueColor: "#0076B6",
    city: "Detroit",
    subreddit: "r/detroitlions",
    abbreviation: "DET",
  },
  {
    id: generateTeamId("NFL", "Green Bay", "packers"),
    name: "Green Bay Packers",
    league: "NFL",
    leagueColor: "#203731",
    city: "Green Bay",
    subreddit: "r/GreenBayPackers",
    abbreviation: "GB",
  },
  {
    id: generateTeamId("NFL", "Houston", "texans"),
    name: "Houston Texans",
    league: "NFL",
    leagueColor: "#03202F",
    city: "Houston",
    subreddit: "r/texans",
    abbreviation: "HOU",
  },
  {
    id: generateTeamId("NFL", "Indianapolis", "colts"),
    name: "Indianapolis Colts",
    league: "NFL",
    leagueColor: "#002C5F",
    city: "Indianapolis",
    subreddit: "r/colts",
    abbreviation: "IND",
  },
  {
    id: generateTeamId("NFL", "Jacksonville", "jaguars"),
    name: "Jacksonville Jaguars",
    league: "NFL",
    leagueColor: "#006778",
    city: "Jacksonville",
    subreddit: "r/jaguars",
    abbreviation: "JAX",
  },
  {
    id: generateTeamId("NFL", "Kansas City", "chiefs"),
    name: "Kansas City Chiefs",
    league: "NFL",
    leagueColor: "#E31837",
    city: "Kansas City",
    subreddit: "r/kansascitychiefs",
    abbreviation: "KC",
  },
  {
    id: generateTeamId("NFL", "Las Vegas", "raiders"),
    name: "Las Vegas Raiders",
    league: "NFL",
    leagueColor: "#000000",
    city: "Las Vegas",
    subreddit: "r/raiders",
    abbreviation: "LV",
  },
  {
    id: generateTeamId("NFL", "Los Angeles", "chargers"),
    name: "Los Angeles Chargers",
    league: "NFL",
    leagueColor: "#0080C6",
    city: "Los Angeles",
    subreddit: "r/chargers",
    abbreviation: "LAC",
  },
  {
    id: generateTeamId("NFL", "Los Angeles", "rams"),
    name: "Los Angeles Rams",
    league: "NFL",
    leagueColor: "#003594",
    city: "Los Angeles",
    subreddit: "r/losangelesrams",
    abbreviation: "LAR",
  },
  {
    id: generateTeamId("NFL", "Miami", "dolphins"),
    name: "Miami Dolphins",
    league: "NFL",
    leagueColor: "#008E97",
    city: "Miami",
    subreddit: "r/miamidolphins",
    abbreviation: "MIA",
  },
  {
    id: generateTeamId("NFL", "Minneapolis", "vikings"),
    name: "Minnesota Vikings",
    league: "NFL",
    leagueColor: "#4F2683",
    city: "Minneapolis",
    subreddit: "r/minnesotavikings",
    abbreviation: "MIN",
  },
  {
    id: generateTeamId("NFL", "New England", "patriots"),
    name: "New England Patriots",
    league: "NFL",
    leagueColor: "#002244",
    city: "New England",
    subreddit: "r/patriots",
    abbreviation: "NE",
  },
  {
    id: generateTeamId("NFL", "New Orleans", "saints"),
    name: "New Orleans Saints",
    league: "NFL",
    leagueColor: "#D3BC8D",
    city: "New Orleans",
    subreddit: "r/saints",
    abbreviation: "NO",
  },
  {
    id: generateTeamId("NFL", "New York", "giants"),
    name: "New York Giants",
    league: "NFL",
    leagueColor: "#0B2265",
    city: "New York",
    subreddit: "r/nygiants",
    abbreviation: "NYG",
  },
  {
    id: generateTeamId("NFL", "New York", "jets"),
    name: "New York Jets",
    league: "NFL",
    leagueColor: "#125740",
    city: "New York",
    subreddit: "r/nyjets",
    abbreviation: "NYJ",
  },
  {
    id: generateTeamId("NFL", "Philadelphia", "eagles"),
    name: "Philadelphia Eagles",
    league: "NFL",
    leagueColor: "#004C54",
    city: "Philadelphia",
    subreddit: "r/eagles",
    abbreviation: "PHI",
  },
  {
    id: generateTeamId("NFL", "Pittsburgh", "steelers"),
    name: "Pittsburgh Steelers",
    league: "NFL",
    leagueColor: "#FFB612",
    city: "Pittsburgh",
    subreddit: "r/steelers",
    abbreviation: "PIT",
  },
  {
    id: generateTeamId("NFL", "San Francisco", "49ers"),
    name: "San Francisco 49ers",
    league: "NFL",
    leagueColor: "#AA0000",
    city: "San Francisco",
    subreddit: "r/49ers",
    abbreviation: "SF",
  },
  {
    id: generateTeamId("NFL", "Seattle", "seahawks"),
    name: "Seattle Seahawks",
    league: "NFL",
    leagueColor: "#002244",
    city: "Seattle",
    subreddit: "r/seahawks",
    abbreviation: "SEA",
  },
  {
    id: generateTeamId("NFL", "Tampa Bay", "buccaneers"),
    name: "Tampa Bay Buccaneers",
    league: "NFL",
    leagueColor: "#D50A0A",
    city: "Tampa Bay",
    subreddit: "r/buccaneers",
    abbreviation: "TB",
  },
  {
    id: generateTeamId("NFL", "Nashville", "titans"),
    name: "Tennessee Titans",
    league: "NFL",
    leagueColor: "#0C2340",
    city: "Nashville",
    subreddit: "r/tennesseetitans",
    abbreviation: "TEN",
  },
  {
    id: generateTeamId("NFL", "Washington", "commanders"),
    name: "Washington Commanders",
    league: "NFL",
    leagueColor: "#5A1414",
    city: "Washington",
    subreddit: "r/commanders",
    abbreviation: "WAS",
  },

  // NBA Teams (30 teams)
  {
    id: generateTeamId("NBA", "Atlanta", "hawks"),
    name: "Atlanta Hawks",
    league: "NBA",
    leagueColor: "#E03A3E",
    city: "Atlanta",
    subreddit: "r/AtlantaHawks",
    abbreviation: "ATL",
  },
  {
    id: generateTeamId("NBA", "Boston", "celtics"),
    name: "Boston Celtics",
    league: "NBA",
    leagueColor: "#007A33",
    city: "Boston",
    subreddit: "r/bostonceltics",
    abbreviation: "BOS",
  },
  {
    id: generateTeamId("NBA", "Brooklyn", "nets"),
    name: "Brooklyn Nets",
    league: "NBA",
    leagueColor: "#000000",
    city: "Brooklyn",
    subreddit: "r/GoNets",
    abbreviation: "BKN",
  },
  {
    id: generateTeamId("NBA", "Charlotte", "hornets"),
    name: "Charlotte Hornets",
    league: "NBA",
    leagueColor: "#1D1160",
    city: "Charlotte",
    subreddit: "r/CharlotteHornets",
    abbreviation: "CHA",
  },
  {
    id: generateTeamId("NBA", "Chicago", "bulls"),
    name: "Chicago Bulls",
    league: "NBA",
    leagueColor: "#CE1141",
    city: "Chicago",
    subreddit: "r/chicagobulls",
    abbreviation: "CHI",
  },
  {
    id: generateTeamId("NBA", "Cleveland", "cavaliers"),
    name: "Cleveland Cavaliers",
    league: "NBA",
    leagueColor: "#860038",
    city: "Cleveland",
    subreddit: "r/clevelandcavs",
    abbreviation: "CLE",
  },
  {
    id: generateTeamId("NBA", "Dallas", "mavericks"),
    name: "Dallas Mavericks",
    league: "NBA",
    leagueColor: "#00538C",
    city: "Dallas",
    subreddit: "r/Mavericks",
    abbreviation: "DAL",
  },
  {
    id: generateTeamId("NBA", "Denver", "nuggets"),
    name: "Denver Nuggets",
    league: "NBA",
    leagueColor: "#0E2240",
    city: "Denver",
    subreddit: "r/DenverNuggets",
    abbreviation: "DEN",
  },
  {
    id: generateTeamId("NBA", "Detroit", "pistons"),
    name: "Detroit Pistons",
    league: "NBA",
    leagueColor: "#C8102E",
    city: "Detroit",
    subreddit: "r/DetroitPistons",
    abbreviation: "DET",
  },
  {
    id: generateTeamId("NBA", "San Francisco", "warriors"),
    name: "Golden State Warriors",
    league: "NBA",
    leagueColor: "#1D428A",
    city: "San Francisco",
    subreddit: "r/warriors",
    abbreviation: "GSW",
  },
  {
    id: generateTeamId("NBA", "Houston", "rockets"),
    name: "Houston Rockets",
    league: "NBA",
    leagueColor: "#CE1141",
    city: "Houston",
    subreddit: "r/rockets",
    abbreviation: "HOU",
  },
  {
    id: generateTeamId("NBA", "Indianapolis", "pacers"),
    name: "Indiana Pacers",
    league: "NBA",
    leagueColor: "#002D62",
    city: "Indianapolis",
    subreddit: "r/pacers",
    abbreviation: "IND",
  },
  {
    id: generateTeamId("NBA", "Los Angeles", "clippers"),
    name: "Los Angeles Clippers",
    league: "NBA",
    leagueColor: "#C8102E",
    city: "Los Angeles",
    subreddit: "r/LAClippers",
    abbreviation: "LAC",
  },
  {
    id: generateTeamId("NBA", "Los Angeles", "lakers"),
    name: "Los Angeles Lakers",
    league: "NBA",
    leagueColor: "#552583",
    city: "Los Angeles",
    subreddit: "r/lakers",
    abbreviation: "LAL",
  },
  {
    id: generateTeamId("NBA", "Memphis", "grizzlies"),
    name: "Memphis Grizzlies",
    league: "NBA",
    leagueColor: "#5D76A9",
    city: "Memphis",
    subreddit: "r/memphisgrizzlies",
    abbreviation: "MEM",
  },
  {
    id: generateTeamId("NBA", "Miami", "heat"),
    name: "Miami Heat",
    league: "NBA",
    leagueColor: "#98002E",
    city: "Miami",
    subreddit: "r/heat",
    abbreviation: "MIA",
  },
  {
    id: generateTeamId("NBA", "Milwaukee", "bucks"),
    name: "Milwaukee Bucks",
    league: "NBA",
    leagueColor: "#00471B",
    city: "Milwaukee",
    subreddit: "r/MkeBucks",
    abbreviation: "MIL",
  },
  {
    id: generateTeamId("NBA", "Minneapolis", "timberwolves"),
    name: "Minnesota Timberwolves",
    league: "NBA",
    leagueColor: "#0C2340",
    city: "Minneapolis",
    subreddit: "r/timberwolves",
    abbreviation: "MIN",
  },
  {
    id: generateTeamId("NBA", "New Orleans", "pelicans"),
    name: "New Orleans Pelicans",
    league: "NBA",
    leagueColor: "#0C2340",
    city: "New Orleans",
    subreddit: "r/NOLAPelicans",
    abbreviation: "NOP",
  },
  {
    id: generateTeamId("NBA", "New York", "knicks"),
    name: "New York Knicks",
    league: "NBA",
    leagueColor: "#F58426",
    city: "New York",
    subreddit: "r/NYKnicks",
    abbreviation: "NYK",
  },
  {
    id: generateTeamId("NBA", "Oklahoma City", "thunder"),
    name: "Oklahoma City Thunder",
    league: "NBA",
    leagueColor: "#007AC1",
    city: "Oklahoma City",
    subreddit: "r/Thunder",
    abbreviation: "OKC",
  },
  {
    id: generateTeamId("NBA", "Orlando", "magic"),
    name: "Orlando Magic",
    league: "NBA",
    leagueColor: "#0077C0",
    city: "Orlando",
    subreddit: "r/orlandomagic",
    abbreviation: "ORL",
  },
  {
    id: generateTeamId("NBA", "Philadelphia", "76ers"),
    name: "Philadelphia 76ers",
    league: "NBA",
    leagueColor: "#006BB6",
    city: "Philadelphia",
    subreddit: "r/sixers",
  },
  {
    id: generateTeamId("NBA", "Phoenix", "suns"),
    name: "Phoenix Suns",
    league: "NBA",
    leagueColor: "#1D1160",
    city: "Phoenix",
    subreddit: "r/suns",
  },
  {
    id: generateTeamId("NBA", "Portland", "trail-blazers"),
    name: "Portland Trail Blazers",
    league: "NBA",
    leagueColor: "#E03A3E",
    city: "Portland",
    subreddit: "r/ripcity",
  },
  {
    id: generateTeamId("NBA", "Sacramento", "kings"),
    name: "Sacramento Kings",
    league: "NBA",
    leagueColor: "#5A2D81",
    city: "Sacramento",
    subreddit: "r/kings",
  },
  {
    id: generateTeamId("NBA", "San Antonio", "spurs"),
    name: "San Antonio Spurs",
    league: "NBA",
    leagueColor: "#C4CED4",
    city: "San Antonio",
    subreddit: "r/nbaspurs",
    abbreviation: "SAS",
  },
  {
    id: generateTeamId("NBA", "Toronto", "raptors"),
    name: "Toronto Raptors",
    league: "NBA",
    leagueColor: "#CE1141",
    city: "Toronto",
    subreddit: "r/torontoraptors",
    abbreviation: "TOR",
  },
  {
    id: generateTeamId("NBA", "Salt Lake City", "jazz"),
    name: "Utah Jazz",
    league: "NBA",
    leagueColor: "#002B5C",
    city: "Salt Lake City",
    subreddit: "r/UtahJazz",
    abbreviation: "UTA",
  },
  {
    id: generateTeamId("NBA", "Washington", "wizards"),
    name: "Washington Wizards",
    league: "NBA",
    leagueColor: "#002B5C",
    city: "Washington",
    subreddit: "r/washingtonwizards",
    abbreviation: "WAS",
  },

  // MLB Teams (30 teams)
  {
    id: generateTeamId("MLB", "Phoenix", "diamondbacks"),
    name: "Arizona Diamondbacks",
    league: "MLB",
    leagueColor: "#A71930",
    city: "Phoenix",
    subreddit: "r/azdiamondbacks",
    abbreviation: "ARI",
  },
  {
    id: generateTeamId("MLB", "Atlanta", "braves"),
    name: "Atlanta Braves",
    league: "MLB",
    leagueColor: "#CE1141",
    city: "Atlanta",
    subreddit: "r/Braves",
    abbreviation: "ATL",
  },
  {
    id: generateTeamId("MLB", "Baltimore", "orioles"),
    name: "Baltimore Orioles",
    league: "MLB",
    leagueColor: "#DF4601",
    city: "Baltimore",
    subreddit: "r/Orioles",
    abbreviation: "BAL",
  },
  {
    id: generateTeamId("MLB", "Boston", "red-sox"),
    name: "Boston Red Sox",
    league: "MLB",
    leagueColor: "#BD3039",
    city: "Boston",
    subreddit: "r/RedSox",
    abbreviation: "BOS",
  },
  {
    id: generateTeamId("MLB", "Chicago", "cubs"),
    name: "Chicago Cubs",
    league: "MLB",
    leagueColor: "#0E3386",
    city: "Chicago",
    subreddit: "r/CHICubs",
    abbreviation: "CHC",
  },
  {
    id: generateTeamId("MLB", "Chicago", "white-sox"),
    name: "Chicago White Sox",
    league: "MLB",
    leagueColor: "#27251F",
    city: "Chicago",
    subreddit: "r/WhiteSox",
    abbreviation: "CWS",
  },
  {
    id: generateTeamId("MLB", "Cincinnati", "reds"),
    name: "Cincinnati Reds",
    league: "MLB",
    leagueColor: "#C6011F",
    city: "Cincinnati",
    subreddit: "r/Reds",
    abbreviation: "CIN",
  },
  {
    id: generateTeamId("MLB", "Cleveland", "guardians"),
    name: "Cleveland Guardians",
    league: "MLB",
    leagueColor: "#E31937",
    city: "Cleveland",
    subreddit: "r/ClevelandGuardians",
    abbreviation: "CLE",
  },
  {
    id: generateTeamId("MLB", "Denver", "rockies"),
    name: "Colorado Rockies",
    league: "MLB",
    leagueColor: "#33006F",
    city: "Denver",
    subreddit: "r/ColoradoRockies",
    abbreviation: "COL",
  },
  {
    id: generateTeamId("MLB", "Detroit", "tigers"),
    name: "Detroit Tigers",
    league: "MLB",
    leagueColor: "#0C2340",
    city: "Detroit",
    subreddit: "r/MotorCityKitties",
    abbreviation: "DET",
  },
  {
    id: generateTeamId("MLB", "Houston", "astros"),
    name: "Houston Astros",
    league: "MLB",
    leagueColor: "#002D62",
    city: "Houston",
    subreddit: "r/Astros",
    abbreviation: "HOU",
  },
  {
    id: generateTeamId("MLB", "Kansas City", "royals"),
    name: "Kansas City Royals",
    league: "MLB",
    leagueColor: "#004687",
    city: "Kansas City",
    subreddit: "r/Royals",
    abbreviation: "KC",
  },
  {
    id: generateTeamId("MLB", "Anaheim", "angels"),
    name: "Los Angeles Angels",
    league: "MLB",
    leagueColor: "#BA0021",
    city: "Anaheim",
    subreddit: "r/AngelsBaseball",
    abbreviation: "LAA",
  },
  {
    id: generateTeamId("MLB", "Los Angeles", "dodgers"),
    name: "Los Angeles Dodgers",
    league: "MLB",
    leagueColor: "#005A9C",
    city: "Los Angeles",
    subreddit: "r/Dodgers",
    abbreviation: "LAD",
  },
  {
    id: generateTeamId("MLB", "Miami", "marlins"),
    name: "Miami Marlins",
    league: "MLB",
    leagueColor: "#00A3E0",
    city: "Miami",
    subreddit: "r/letsgofish",
    abbreviation: "MIA",
  },
  {
    id: generateTeamId("MLB", "Milwaukee", "brewers"),
    name: "Milwaukee Brewers",
    league: "MLB",
    leagueColor: "#12284B",
    city: "Milwaukee",
    subreddit: "r/Brewers",
    abbreviation: "MIL",
  },
  {
    id: generateTeamId("MLB", "Minneapolis", "twins"),
    name: "Minnesota Twins",
    league: "MLB",
    leagueColor: "#002B5C",
    city: "Minneapolis",
    subreddit: "r/minnesotatwins",
    abbreviation: "MIN",
  },
  {
    id: generateTeamId("MLB", "New York", "mets"),
    name: "New York Mets",
    league: "MLB",
    leagueColor: "#002D72",
    city: "New York",
    subreddit: "r/NewYorkMets",
    abbreviation: "NYM",
  },
  {
    id: generateTeamId("MLB", "New York", "yankees"),
    name: "New York Yankees",
    league: "MLB",
    leagueColor: "#132448",
    city: "New York",
    subreddit: "r/NYYankees",
    abbreviation: "NYY",
  },
  {
    id: generateTeamId("MLB", "Oakland", "athletics"),
    name: "Oakland Athletics",
    league: "MLB",
    leagueColor: "#003831",
    city: "Oakland",
    subreddit: "r/OaklandAthletics",
    abbreviation: "OAK",
  },
  {
    id: generateTeamId("MLB", "Philadelphia", "phillies"),
    name: "Philadelphia Phillies",
    league: "MLB",
    leagueColor: "#E81828",
    city: "Philadelphia",
    subreddit: "r/Phillies",
    abbreviation: "PHI",
  },
  {
    id: generateTeamId("MLB", "Pittsburgh", "pirates"),
    name: "Pittsburgh Pirates",
    league: "MLB",
    leagueColor: "#FDB827",
    city: "Pittsburgh",
    subreddit: "r/Buccos",
    abbreviation: "PIT",
  },
  {
    id: generateTeamId("MLB", "San Diego", "padres"),
    name: "San Diego Padres",
    league: "MLB",
    leagueColor: "#2F241D",
    city: "San Diego",
    subreddit: "r/Padres",
    abbreviation: "SD",
  },
  {
    id: generateTeamId("MLB", "San Francisco", "giants"),
    name: "San Francisco Giants",
    league: "MLB",
    leagueColor: "#FD5A1E",
    city: "San Francisco",
    subreddit: "r/SFGiants",
    abbreviation: "SF",
  },
  {
    id: generateTeamId("MLB", "Seattle", "mariners"),
    name: "Seattle Mariners",
    league: "MLB",
    leagueColor: "#0C2C56",
    city: "Seattle",
    subreddit: "r/Mariners",
    abbreviation: "SEA",
  },
  {
    id: generateTeamId("MLB", "St. Louis", "cardinals"),
    name: "St. Louis Cardinals",
    league: "MLB",
    leagueColor: "#C41E3A",
    city: "St. Louis",
    subreddit: "r/Cardinals",
    abbreviation: "STL",
  },
  {
    id: generateTeamId("MLB", "St. Petersburg", "rays"),
    name: "Tampa Bay Rays",
    league: "MLB",
    leagueColor: "#092C5C",
    city: "St. Petersburg",
    subreddit: "r/TampaBayRays",
    abbreviation: "TB",
  },
  {
    id: generateTeamId("MLB", "Arlington", "rangers"),
    name: "Texas Rangers",
    league: "MLB",
    leagueColor: "#003278",
    city: "Arlington",
    subreddit: "r/texasrangers",
    abbreviation: "TEX",
  },
  {
    id: generateTeamId("MLB", "Toronto", "blue-jays"),
    name: "Toronto Blue Jays",
    league: "MLB",
    leagueColor: "#134A8E",
    city: "Toronto",
    subreddit: "r/Torontobluejays",
    abbreviation: "TOR",
  },
  {
    id: generateTeamId("MLB", "Washington", "nationals"),
    name: "Washington Nationals",
    league: "MLB",
    leagueColor: "#AB0003",
    city: "Washington",
    subreddit: "r/Nationals",
    abbreviation: "WSH",
  },

  // NHL Teams (32 teams)
  {
    id: generateTeamId("NHL", "Anaheim", "ducks"),
    name: "Anaheim Ducks",
    league: "NHL",
    leagueColor: "#F47A38",
    city: "Anaheim",
    subreddit: "r/anaheimducks",
    abbreviation: "ANA",
  },
  {
    id: generateTeamId("NHL", "Tempe", "coyotes"),
    name: "Arizona Coyotes",
    league: "NHL",
    leagueColor: "#8C2633",
    city: "Tempe",
    subreddit: "r/coyotes",
    abbreviation: "ARI",
  },
  {
    id: generateTeamId("NHL", "Boston", "bruins"),
    name: "Boston Bruins",
    league: "NHL",
    leagueColor: "#FFB81C",
    city: "Boston",
    subreddit: "r/bostonbruins",
    abbreviation: "BOS",
  },
  {
    id: generateTeamId("NHL", "Buffalo", "sabres"),
    name: "Buffalo Sabres",
    league: "NHL",
    leagueColor: "#002654",
    city: "Buffalo",
    subreddit: "r/sabres",
    abbreviation: "BUF",
  },
  {
    id: generateTeamId("NHL", "Calgary", "flames"),
    name: "Calgary Flames",
    league: "NHL",
    leagueColor: "#C8102E",
    city: "Calgary",
    subreddit: "r/calgaryflames",
    abbreviation: "CGY",
  },
  {
    id: generateTeamId("NHL", "Raleigh", "hurricanes"),
    name: "Carolina Hurricanes",
    league: "NHL",
    leagueColor: "#CC0000",
    city: "Raleigh",
    subreddit: "r/canes",
    abbreviation: "CAR",
  },
  {
    id: generateTeamId("NHL", "Chicago", "blackhawks"),
    name: "Chicago Blackhawks",
    league: "NHL",
    leagueColor: "#CF0A2C",
    city: "Chicago",
    subreddit: "r/hawks",
    abbreviation: "CHI",
  },
  {
    id: generateTeamId("NHL", "Denver", "avalanche"),
    name: "Colorado Avalanche",
    league: "NHL",
    leagueColor: "#6F263D",
    city: "Denver",
    subreddit: "r/coloradoavalanche",
    abbreviation: "COL",
  },
  {
    id: generateTeamId("NHL", "Columbus", "blue-jackets"),
    name: "Columbus Blue Jackets",
    league: "NHL",
    leagueColor: "#002654",
    city: "Columbus",
    subreddit: "r/bluejackets",
    abbreviation: "CBJ",
  },
  {
    id: generateTeamId("NHL", "Dallas", "stars"),
    name: "Dallas Stars",
    league: "NHL",
    leagueColor: "#006847",
    city: "Dallas",
    subreddit: "r/dallasstars",
    abbreviation: "DAL",
  },
  {
    id: generateTeamId("NHL", "Detroit", "red-wings"),
    name: "Detroit Red Wings",
    league: "NHL",
    leagueColor: "#CE1126",
    city: "Detroit",
    subreddit: "r/detroitredwings",
    abbreviation: "DET",
  },
  {
    id: generateTeamId("NHL", "Edmonton", "oilers"),
    name: "Edmonton Oilers",
    league: "NHL",
    leagueColor: "#041E42",
    city: "Edmonton",
    subreddit: "r/edmontonoilers",
    abbreviation: "EDM",
  },
  {
    id: generateTeamId("NHL", "Sunrise", "panthers"),
    name: "Florida Panthers",
    league: "NHL",
    leagueColor: "#041E42",
    city: "Sunrise",
    subreddit: "r/floridapanthers",
    abbreviation: "FLA",
  },
  {
    id: generateTeamId("NHL", "Los Angeles", "kings"),
    name: "Los Angeles Kings",
    league: "NHL",
    leagueColor: "#111111",
    city: "Los Angeles",
    subreddit: "r/losangeleskings",
    abbreviation: "LAK",
  },
  {
    id: generateTeamId("NHL", "Saint Paul", "wild"),
    name: "Minnesota Wild",
    league: "NHL",
    leagueColor: "#154734",
    city: "Saint Paul",
    subreddit: "r/wildhockey",
    abbreviation: "MIN",
  },
  {
    id: generateTeamId("NHL", "Montreal", "canadiens"),
    name: "Montreal Canadiens",
    league: "NHL",
    leagueColor: "#AF1E2D",
    city: "Montreal",
    subreddit: "r/habs",
    abbreviation: "MTL",
  },
  {
    id: generateTeamId("NHL", "Nashville", "predators"),
    name: "Nashville Predators",
    league: "NHL",
    leagueColor: "#FFB81C",
    city: "Nashville",
    subreddit: "r/predators",
    abbreviation: "NSH",
  },
  {
    id: generateTeamId("NHL", "Newark", "devils"),
    name: "New Jersey Devils",
    league: "NHL",
    leagueColor: "#CE1126",
    city: "Newark",
    subreddit: "r/devils",
    abbreviation: "NJD",
  },
  {
    id: generateTeamId("NHL", "Elmont", "islanders"),
    name: "New York Islanders",
    league: "NHL",
    leagueColor: "#F47A38",
    city: "Elmont",
    subreddit: "r/newyorkislanders",
    abbreviation: "NYI",
  },
  {
    id: generateTeamId("NHL", "New York", "rangers"),
    name: "New York Rangers",
    league: "NHL",
    leagueColor: "#0038A8",
    city: "New York",
    subreddit: "r/rangers",
    abbreviation: "NYR",
  },
  {
    id: generateTeamId("NHL", "Ottawa", "senators"),
    name: "Ottawa Senators",
    league: "NHL",
    leagueColor: "#C52032",
    city: "Ottawa",
    subreddit: "r/ottawasenators",
    abbreviation: "OTT",
  },
  {
    id: generateTeamId("NHL", "Philadelphia", "flyers"),
    name: "Philadelphia Flyers",
    league: "NHL",
    leagueColor: "#F74902",
    city: "Philadelphia",
    subreddit: "r/flyers",
    abbreviation: "PHI",
  },
  {
    id: generateTeamId("NHL", "Pittsburgh", "penguins"),
    name: "Pittsburgh Penguins",
    league: "NHL",
    leagueColor: "#CFC493",
    city: "Pittsburgh",
    subreddit: "r/penguins",
    abbreviation: "PIT",
  },
  {
    id: generateTeamId("NHL", "San Jose", "sharks"),
    name: "San Jose Sharks",
    league: "NHL",
    leagueColor: "#006D75",
    city: "San Jose",
    subreddit: "r/sanjosesharks",
    abbreviation: "SJS",
  },
  {
    id: generateTeamId("NHL", "Seattle", "kraken"),
    name: "Seattle Kraken",
    league: "NHL",
    leagueColor: "#001628",
    city: "Seattle",
    subreddit: "r/seattlekraken",
    abbreviation: "SEA",
  },
  {
    id: generateTeamId("NHL", "St. Louis", "blues"),
    name: "St. Louis Blues",
    league: "NHL",
    leagueColor: "#002F87",
    city: "St. Louis",
    subreddit: "r/stlouisblues",
    abbreviation: "STL",
  },
  {
    id: generateTeamId("NHL", "Tampa", "lightning"),
    name: "Tampa Bay Lightning",
    league: "NHL",
    leagueColor: "#002868",
    city: "Tampa",
    subreddit: "r/tampabaylightning",
    abbreviation: "TBL",
  },
  {
    id: generateTeamId("NHL", "Toronto", "maple-leafs"),
    name: "Toronto Maple Leafs",
    league: "NHL",
    leagueColor: "#003E7E",
    city: "Toronto",
    subreddit: "r/leafs",
    abbreviation: "TOR",
  },
  {
    id: generateTeamId("NHL", "Vancouver", "canucks"),
    name: "Vancouver Canucks",
    league: "NHL",
    leagueColor: "#001F5B",
    city: "Vancouver",
    subreddit: "r/canucks",
    abbreviation: "VAN",
  },
  {
    id: generateTeamId("NHL", "Las Vegas", "golden-knights"),
    name: "Vegas Golden Knights",
    league: "NHL",
    leagueColor: "#B4975A",
    city: "Las Vegas",
    subreddit: "r/goldenknights",
    abbreviation: "VGK",
  },
  {
    id: generateTeamId("NHL", "Washington", "capitals"),
    name: "Washington Capitals",
    league: "NHL",
    leagueColor: "#C8102E",
    city: "Washington",
    subreddit: "r/caps",
    abbreviation: "WSH",
  },
  {
    id: generateTeamId("NHL", "Winnipeg", "jets"),
    name: "Winnipeg Jets",
    league: "NHL",
    leagueColor: "#041E42",
    city: "Winnipeg",
    subreddit: "r/winnipegjets",
    abbreviation: "WPG",
  },

  // MLS Teams (29 teams)
  {
    id: generateTeamId("MLS", "Atlanta", "united-fc"),
    name: "Atlanta United FC",
    league: "MLS",
    leagueColor: "#800F2F",
    city: "Atlanta",
    subreddit: "r/AtlantaUnitedFC",
    abbreviation: "ATL",
  },
  {
    id: generateTeamId("MLS", "Austin", "fc"),
    name: "Austin FC",
    league: "MLS",
    leagueColor: "#00B140",
    city: "Austin",
    subreddit: "r/AustinFC",
    abbreviation: "ATX",
  },
  {
    id: generateTeamId("MLS", "Charlotte", "fc"),
    name: "Charlotte FC",
    league: "MLS",
    leagueColor: "#1E1E1E",
    city: "Charlotte",
    subreddit: "r/CharlotteFC",
    abbreviation: "CLT",
  },
  {
    id: generateTeamId("MLS", "Chicago", "fire-fc"),
    name: "Chicago Fire FC",
    league: "MLS",
    leagueColor: "#0B5394",
    city: "Chicago",
    subreddit: "r/ChicagoFire",
    abbreviation: "CHI",
  },
  {
    id: generateTeamId("MLS", "Cincinnati", "fc-cincinnati"),
    name: "FC Cincinnati",
    league: "MLS",
    leagueColor: "#F6F6F6",
    city: "Cincinnati",
    subreddit: "r/FCCincinnati",
    abbreviation: "CIN",
  },
  {
    id: generateTeamId("MLS", "Commerce City", "rapids"),
    name: "Colorado Rapids",
    league: "MLS",
    leagueColor: "#862633",
    city: "Commerce City",
    subreddit: "r/ColoradoRapids",
    abbreviation: "COL",
  },
  {
    id: generateTeamId("MLS", "Columbus", "crew"),
    name: "Columbus Crew",
    league: "MLS",
    leagueColor: "#FDB913",
    city: "Columbus",
    subreddit: "r/TheMassive",
    abbreviation: "CLB",
  },
  {
    id: generateTeamId("MLS", "Washington", "dc-united"),
    name: "D.C. United",
    league: "MLS",
    leagueColor: "#000000",
    city: "Washington",
    subreddit: "r/DCUnited",
    abbreviation: "DC",
  },
  {
    id: generateTeamId("MLS", "Frisco", "fc-dallas"),
    name: "FC Dallas",
    league: "MLS",
    leagueColor: "#D11241",
    city: "Frisco",
    subreddit: "r/FCDallas",
    abbreviation: "DAL",
  },
  {
    id: generateTeamId("MLS", "Houston", "dynamo-fc"),
    name: "Houston Dynamo FC",
    league: "MLS",
    leagueColor: "#F68712",
    city: "Houston",
    subreddit: "r/dynamo",
    abbreviation: "HOU",
  },
  {
    id: generateTeamId("MLS", "Miami", "inter-miami-cf"),
    name: "Inter Miami CF",
    league: "MLS",
    leagueColor: "#000000",
    city: "Miami",
    subreddit: "r/InterMiamiCF",
    abbreviation: "MIA",
  },
  {
    id: generateTeamId("MLS", "Kansas City", "sporting-kansas-city"),
    name: "Sporting Kansas City",
    league: "MLS",
    leagueColor: "#0C2340",
    city: "Kansas City",
    subreddit: "r/SportingKC",
    abbreviation: "SKC",
  },
  {
    id: generateTeamId("MLS", "Carson", "la-galaxy"),
    name: "LA Galaxy",
    league: "MLS",
    leagueColor: "#00245D",
    city: "Carson",
    subreddit: "r/LAGalaxy",
    abbreviation: "LAG",
  },
  {
    id: generateTeamId("MLS", "Los Angeles", "los-angeles-fc"),
    name: "Los Angeles FC",
    league: "MLS",
    leagueColor: "#000000",
    city: "Los Angeles",
    subreddit: "r/LACity",
    abbreviation: "LAFC",
  },
  {
    id: generateTeamId("MLS", "Saint Paul", "minnesota-united-fc"),
    name: "Minnesota United FC",
    league: "MLS",
    leagueColor: "#7C0020",
    city: "Saint Paul",
    subreddit: "r/minnesotaunited",
    abbreviation: "MIN",
  },
  {
    id: generateTeamId("MLS", "Montreal", "cf-montreal"),
    name: "CF Montréal",
    league: "MLS",
    leagueColor: "#000000",
    city: "Montreal",
    subreddit: "r/CFMontreal",
    abbreviation: "MTL",
  },
  {
    id: generateTeamId("MLS", "Nashville", "nashville-sc"),
    name: "Nashville SC",
    league: "MLS",
    leagueColor: "#FFE500",
    city: "Nashville",
    subreddit: "r/NashvilleSC",
    abbreviation: "NSH",
  },
  {
    id: generateTeamId("MLS", "Foxborough", "new-england-revolution"),
    name: "New England Revolution",
    league: "MLS",
    leagueColor: "#0C2340",
    city: "Foxborough",
    subreddit: "r/NewEnglandRevolution",
    abbreviation: "NE",
  },
  {
    id: generateTeamId("MLS", "New York", "new-york-city-fc"),
    name: "New York City FC",
    league: "MLS",
    leagueColor: "#6CACE4",
    city: "New York",
    subreddit: "r/NYCFC",
    abbreviation: "NYC",
  },
  {
    id: generateTeamId("MLS", "Harrison", "new-york-red-bulls"),
    name: "New York Red Bulls",
    league: "MLS",
    leagueColor: "#ED1C24",
    city: "Harrison",
    subreddit: "r/NYRB",
    abbreviation: "RBNY",
  },
  {
    id: generateTeamId("MLS", "Orlando", "orlando-city-sc"),
    name: "Orlando City SC",
    league: "MLS",
    leagueColor: "#6C1D45",
    city: "Orlando",
    subreddit: "r/OCLions",
    abbreviation: "ORL",
  },
  {
    id: generateTeamId("MLS", "Chester", "philadelphia-union"),
    name: "Philadelphia Union",
    league: "MLS",
    leagueColor: "#0C2340",
    city: "Chester",
    subreddit: "r/PhillyUnion",
    abbreviation: "PHI",
  },
  {
    id: generateTeamId("MLS", "Portland", "timbers"),
    name: "Portland Timbers",
    league: "MLS",
    leagueColor: "#004812",
    city: "Portland",
    subreddit: "r/timbers",
    abbreviation: "POR",
  },
  {
    id: generateTeamId("MLS", "Sandy", "real-salt-lake"),
    name: "Real Salt Lake",
    league: "MLS",
    leagueColor: "#A5051B",
    city: "Sandy",
    subreddit: "r/realSaltLake",
    abbreviation: "RSL",
  },
  {
    id: generateTeamId("MLS", "San Jose", "earthquakes"),
    name: "San Jose Earthquakes",
    league: "MLS",
    leagueColor: "#0066CC",
    city: "San Jose",
    subreddit: "r/SJEarthquakes",
    abbreviation: "SJ",
  },
  {
    id: generateTeamId("MLS", "Seattle", "sounders-fc"),
    name: "Seattle Sounders FC",
    league: "MLS",
    leagueColor: "#4F8A10",
    city: "Seattle",
    subreddit: "r/SoundersFC",
    abbreviation: "SEA",
  },
  {
    id: generateTeamId("MLS", "St. Louis", "st-louis-city-sc"),
    name: "St. Louis City SC",
    league: "MLS",
    leagueColor: "#C8102E",
    city: "St. Louis",
    subreddit: "r/StLouisCITY",
    abbreviation: "STL",
  },
  {
    id: generateTeamId("MLS", "Toronto", "toronto-fc"),
    name: "Toronto FC",
    league: "MLS",
    leagueColor: "#E31937",
    city: "Toronto",
    subreddit: "r/TorontoFC",
    abbreviation: "TOR",
  },
  {
    id: generateTeamId("MLS", "Vancouver", "whitecaps-fc"),
    name: "Vancouver Whitecaps FC",
    league: "MLS",
    leagueColor: "#00245D",
    city: "Vancouver",
    subreddit: "r/whitecapsfc",
    abbreviation: "VAN",
  },
];


// Helper function to get team subreddit from team name (for score cards)
export const getTeamSubredditByName = (teamName: string, league: League = League.MLB): string | null => {
  if (!teamName) return null;
  
  // Create Fuse instance for fuzzy matching
  const fuse = new Fuse(allTeams, {
    keys: ['name'], // Search in the 'name' field
    includeScore: true,
    threshold: 0.4, // Lower = stricter matching (0.0 = exact, 1.0 = match anything)
    distance: 100,  // Maximum distance for a match
  });
  
  // Search for the team
  const results = fuse.search(teamName);
  
  // If we found a match with a good score, return the subreddit
  if (results.length > 0) {
    const { item, score } = results[0];
    // Lower score = better match (0.0 is perfect match)
    // Use case-insensitive comparison for league
    if (score !== undefined && score < 0.3 && item.league.toLowerCase() === league.toLowerCase()) {
      return item.subreddit || null;
    }
  }
  
  return null;
};