use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Inning {
    #[serde(rename = "InningID")]
    pub inning_id: i64,
    #[serde(rename = "GameID")]
    pub game_id: i64,
    #[serde(rename = "InningNumber")]
    pub inning_number: Option<i32>,
    #[serde(rename = "AwayTeamRuns")]
    pub away_team_runs: Option<i32>,
    #[serde(rename = "HomeTeamRuns")]
    pub home_team_runs: Option<i32>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SeriesInfo {
    #[serde(rename = "HomeTeamWins")]
    pub home_team_wins: Option<i32>,
    #[serde(rename = "AwayTeamWins")]
    pub away_team_wins: Option<i32>,
    #[serde(rename = "GameNumber")]
    pub game_number: Option<i32>,
    #[serde(rename = "MaxLength")]
    pub max_length: Option<i32>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Game {
    #[serde(rename = "GameID")]
    pub game_id: i64,
    #[serde(rename = "Season")]
    pub season: Option<i32>,
    #[serde(rename = "SeasonType")]
    pub season_type: Option<i32>,
    #[serde(rename = "Status")]
    pub status: Option<String>,
    #[serde(rename = "Day")]
    pub day: String,
    #[serde(rename = "DateTime")]
    pub date_time: String,
    #[serde(rename = "AwayTeam")]
    pub away_team: String,
    #[serde(rename = "HomeTeam")]
    pub home_team: String,
    #[serde(rename = "AwayTeamID")]
    pub away_team_id: Option<i32>,
    #[serde(rename = "HomeTeamID")]
    pub home_team_id: Option<i32>,
    #[serde(rename = "RescheduledGameID")]
    pub rescheduled_game_id: Option<i64>,
    #[serde(rename = "StadiumID")]
    pub stadium_id: Option<i32>,
    #[serde(rename = "Channel")]
    pub channel: Option<String>,
    #[serde(rename = "Inning")]
    pub inning: Option<i32>,
    #[serde(rename = "InningHalf")]
    pub inning_half: Option<String>,
    #[serde(rename = "AwayTeamRuns")]
    pub away_team_runs: Option<i32>,
    #[serde(rename = "HomeTeamRuns")]
    pub home_team_runs: Option<i32>,
    #[serde(rename = "AwayTeamHits")]
    pub away_team_hits: Option<i32>,
    #[serde(rename = "HomeTeamHits")]
    pub home_team_hits: Option<i32>,
    #[serde(rename = "AwayTeamErrors")]
    pub away_team_errors: Option<i32>,
    #[serde(rename = "HomeTeamErrors")]
    pub home_team_errors: Option<i32>,
    #[serde(rename = "WinningPitcherID")]
    pub winning_pitcher_id: Option<i64>,
    #[serde(rename = "LosingPitcherID")]
    pub losing_pitcher_id: Option<i64>,
    #[serde(rename = "SavingPitcherID")]
    pub saving_pitcher_id: Option<i64>,
    #[serde(rename = "Attendance")]
    pub attendance: Option<i32>,
    #[serde(rename = "AwayTeamProbablePitcherID")]
    pub away_team_probable_pitcher_id: Option<i64>,
    #[serde(rename = "HomeTeamProbablePitcherID")]
    pub home_team_probable_pitcher_id: Option<i64>,
    #[serde(rename = "Outs")]
    pub outs: Option<i32>,
    #[serde(rename = "Balls")]
    pub balls: Option<i32>,
    #[serde(rename = "Strikes")]
    pub strikes: Option<i32>,
    #[serde(rename = "CurrentPitcherID")]
    pub current_pitcher_id: Option<i64>,
    #[serde(rename = "CurrentHitterID")]
    pub current_hitter_id: Option<i64>,
    #[serde(rename = "AwayTeamStartingPitcherID")]
    pub away_team_starting_pitcher_id: Option<i64>,
    #[serde(rename = "HomeTeamStartingPitcherID")]
    pub home_team_starting_pitcher_id: Option<i64>,
    #[serde(rename = "CurrentPitchingTeamID")]
    pub current_pitching_team_id: Option<i32>,
    #[serde(rename = "CurrentHittingTeamID")]
    pub current_hitting_team_id: Option<i32>,
    #[serde(rename = "PointSpread")]
    pub point_spread: Option<f64>,
    #[serde(rename = "OverUnder")]
    pub over_under: Option<f64>,
    #[serde(rename = "AwayTeamMoneyLine")]
    pub away_team_money_line: Option<i32>,
    #[serde(rename = "HomeTeamMoneyLine")]
    pub home_team_money_line: Option<i32>,
    #[serde(rename = "ForecastTempLow")]
    pub forecast_temp_low: Option<i32>,
    #[serde(rename = "ForecastTempHigh")]
    pub forecast_temp_high: Option<i32>,
    #[serde(rename = "ForecastDescription")]
    pub forecast_description: Option<String>,
    #[serde(rename = "ForecastWindChill")]
    pub forecast_wind_chill: Option<i32>,
    #[serde(rename = "ForecastWindSpeed")]
    pub forecast_wind_speed: Option<i32>,
    #[serde(rename = "ForecastWindDirection")]
    pub forecast_wind_direction: Option<i32>,
    #[serde(rename = "RescheduledFromGameID")]
    pub rescheduled_from_game_id: Option<i64>,
    #[serde(rename = "RunnerOnFirst")]
    pub runner_on_first: Option<bool>,
    #[serde(rename = "RunnerOnSecond")]
    pub runner_on_second: Option<bool>,
    #[serde(rename = "RunnerOnThird")]
    pub runner_on_third: Option<bool>,
    #[serde(rename = "AwayTeamStartingPitcher")]
    pub away_team_starting_pitcher: Option<String>,
    #[serde(rename = "HomeTeamStartingPitcher")]
    pub home_team_starting_pitcher: Option<String>,
    #[serde(rename = "CurrentPitcher")]
    pub current_pitcher: Option<String>,
    #[serde(rename = "CurrentHitter")]
    pub current_hitter: Option<String>,
    #[serde(rename = "WinningPitcher")]
    pub winning_pitcher: Option<String>,
    #[serde(rename = "LosingPitcher")]
    pub losing_pitcher: Option<String>,
    #[serde(rename = "SavingPitcher")]
    pub saving_pitcher: Option<String>,
    #[serde(rename = "DueUpHitterID1")]
    pub due_up_hitter_id1: Option<i64>,
    #[serde(rename = "DueUpHitterID2")]
    pub due_up_hitter_id2: Option<i64>,
    #[serde(rename = "DueUpHitterID3")]
    pub due_up_hitter_id3: Option<i64>,
    #[serde(rename = "GlobalGameID")]
    pub global_game_id: i64,
    #[serde(rename = "GlobalAwayTeamID")]
    pub global_away_team_id: i64,
    #[serde(rename = "GlobalHomeTeamID")]
    pub global_home_team_id: i64,
    #[serde(rename = "PointSpreadAwayTeamMoneyLine")]
    pub point_spread_away_team_money_line: Option<i32>,
    #[serde(rename = "PointSpreadHomeTeamMoneyLine")]
    pub point_spread_home_team_money_line: Option<i32>,
    #[serde(rename = "LastPlay")]
    pub last_play: Option<String>,
    #[serde(rename = "IsClosed")]
    pub is_closed: Option<bool>,
    #[serde(rename = "Updated")]
    pub updated: Option<String>,
    #[serde(rename = "GameEndDateTime")]
    pub game_end_date_time: Option<String>,
    #[serde(rename = "HomeRotationNumber")]
    pub home_rotation_number: Option<i32>,
    #[serde(rename = "AwayRotationNumber")]
    pub away_rotation_number: Option<i32>,
    #[serde(rename = "NeutralVenue")]
    pub neutral_venue: Option<bool>,
    #[serde(rename = "InningDescription")]
    pub inning_description: Option<String>,
    #[serde(rename = "OverPayout")]
    pub over_payout: Option<i32>,
    #[serde(rename = "UnderPayout")]
    pub under_payout: Option<i32>,
    #[serde(rename = "DateTimeUTC")]
    pub date_time_utc: Option<String>,
    #[serde(rename = "HomeTeamOpener")]
    pub home_team_opener: Option<bool>,
    #[serde(rename = "AwayTeamOpener")]
    pub away_team_opener: Option<bool>,
    #[serde(rename = "SuspensionResumeDay")]
    pub suspension_resume_day: Option<String>,
    #[serde(rename = "SuspensionResumeDateTime")]
    pub suspension_resume_date_time: Option<String>,
    #[serde(rename = "SeriesInfo")]
    pub series_info: SeriesInfo,
    #[serde(rename = "Innings")]
    pub innings: Vec<Inning>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TeamGame {
    #[serde(rename = "StatID")]
    pub stat_id: i64,
    #[serde(rename = "TeamID")]
    pub team_id: Option<i32>,
    #[serde(rename = "SeasonType")]
    pub season_type: Option<i32>,
    #[serde(rename = "Season")]
    pub season: Option<i32>,
    #[serde(rename = "Name")]
    pub name: Option<String>,
    #[serde(rename = "Team")]
    pub team: Option<String>,
    #[serde(rename = "GlobalTeamID")]
    pub global_team_id: i64,
    #[serde(rename = "GameID")]
    pub game_id: i64,
    #[serde(rename = "OpponentID")]
    pub opponent_id: Option<i32>,
    #[serde(rename = "Opponent")]
    pub opponent: String,
    #[serde(rename = "Day")]
    pub day: String,
    #[serde(rename = "DateTime")]
    pub date_time: String,
    #[serde(rename = "HomeOrAway")]
    pub home_or_away: String,
    #[serde(rename = "IsGameOver")]
    pub is_game_over: Option<bool>,
    #[serde(rename = "GlobalGameID")]
    pub global_game_id: i64,
    #[serde(rename = "GlobalOpponentID")]
    pub global_opponent_id: i64,
    #[serde(rename = "Updated")]
    pub updated: String,
    #[serde(rename = "Games")]
    pub games: Option<f64>,
    #[serde(rename = "FantasyPoints")]
    pub fantasy_points: Option<f64>,
    #[serde(rename = "AtBats")]
    pub at_bats: Option<f64>,
    #[serde(rename = "Runs")]
    pub runs: Option<f64>,
    #[serde(rename = "Hits")]
    pub hits: Option<f64>,
    #[serde(rename = "Singles")]
    pub singles: Option<f64>,
    #[serde(rename = "Doubles")]
    pub doubles: Option<f64>,
    #[serde(rename = "Triples")]
    pub triples: Option<f64>,
    #[serde(rename = "HomeRuns")]
    pub home_runs: Option<f64>,
    #[serde(rename = "RunsBattedIn")]
    pub runs_batted_in: Option<f64>,
    #[serde(rename = "BattingAverage")]
    pub batting_average: Option<f64>,
    #[serde(rename = "Outs")]
    pub outs: Option<f64>,
    #[serde(rename = "Strikeouts")]
    pub strikeouts: Option<f64>,
    #[serde(rename = "Walks")]
    pub walks: Option<f64>,
    #[serde(rename = "HitByPitch")]
    pub hit_by_pitch: Option<f64>,
    #[serde(rename = "Sacrifices")]
    pub sacrifices: Option<f64>,
    #[serde(rename = "SacrificeFlies")]
    pub sacrifice_flies: Option<f64>,
    #[serde(rename = "GroundIntoDoublePlay")]
    pub ground_into_double_play: Option<f64>,
    #[serde(rename = "StolenBases")]
    pub stolen_bases: Option<f64>,
    #[serde(rename = "CaughtStealing")]
    pub caught_stealing: Option<f64>,
    #[serde(rename = "PitchesSeen")]
    pub pitches_seen: Option<f64>,
    #[serde(rename = "OnBasePercentage")]
    pub on_base_percentage: Option<f64>,
    #[serde(rename = "SluggingPercentage")]
    pub slugging_percentage: Option<f64>,
    #[serde(rename = "OnBasePlusSlugging")]
    pub on_base_plus_slugging: Option<f64>,
    #[serde(rename = "Errors")]
    pub errors: Option<f64>,
    #[serde(rename = "Wins")]
    pub wins: Option<f64>,
    #[serde(rename = "Losses")]
    pub losses: Option<f64>,
    #[serde(rename = "Saves")]
    pub saves: Option<f64>,
    #[serde(rename = "InningsPitchedDecimal")]
    pub innings_pitched_decimal: Option<f64>,
    #[serde(rename = "TotalOutsPitched")]
    pub total_outs_pitched: Option<f64>,
    #[serde(rename = "InningsPitchedFull")]
    pub innings_pitched_full: Option<f64>,
    #[serde(rename = "InningsPitchedOuts")]
    pub innings_pitched_outs: Option<f64>,
    #[serde(rename = "EarnedRunAverage")]
    pub earned_run_average: Option<f64>,
    #[serde(rename = "PitchingHits")]
    pub pitching_hits: Option<f64>,
    #[serde(rename = "PitchingRuns")]
    pub pitching_runs: Option<f64>,
    #[serde(rename = "PitchingEarnedRuns")]
    pub pitching_earned_runs: Option<f64>,
    #[serde(rename = "PitchingWalks")]
    pub pitching_walks: Option<f64>,
    #[serde(rename = "PitchingStrikeouts")]
    pub pitching_strikeouts: Option<f64>,
    #[serde(rename = "PitchingHomeRuns")]
    pub pitching_home_runs: Option<f64>,
    #[serde(rename = "PitchesThrown")]
    pub pitches_thrown: Option<f64>,
    #[serde(rename = "PitchesThrownStrikes")]
    pub pitches_thrown_strikes: Option<f64>,
    #[serde(rename = "WalksHitsPerInningsPitched")]
    pub walks_hits_per_innings_pitched: Option<f64>,
    #[serde(rename = "PitchingBattingAverageAgainst")]
    pub pitching_batting_average_against: Option<f64>,
    #[serde(rename = "GrandSlams")]
    pub grand_slams: Option<f64>,
    #[serde(rename = "FantasyPointsFanDuel")]
    pub fantasy_points_fan_duel: Option<f64>,
    #[serde(rename = "FantasyPointsDraftKings")]
    pub fantasy_points_draft_kings: Option<f64>,
    #[serde(rename = "FantasyPointsYahoo")]
    pub fantasy_points_yahoo: Option<f64>,
    #[serde(rename = "PlateAppearances")]
    pub plate_appearances: Option<f64>,
    #[serde(rename = "TotalBases")]
    pub total_bases: Option<f64>,
    #[serde(rename = "FlyOuts")]
    pub fly_outs: Option<f64>,
    #[serde(rename = "GroundOuts")]
    pub ground_outs: Option<f64>,
    #[serde(rename = "LineOuts")]
    pub line_outs: Option<f64>,
    #[serde(rename = "PopOuts")]
    pub pop_outs: Option<f64>,
    #[serde(rename = "IntentionalWalks")]
    pub intentional_walks: Option<f64>,
    #[serde(rename = "ReachedOnError")]
    pub reached_on_error: Option<f64>,
    #[serde(rename = "BallsInPlay")]
    pub balls_in_play: Option<f64>,
    #[serde(rename = "BattingAverageOnBallsInPlay")]
    pub batting_average_on_balls_in_play: Option<f64>,
    #[serde(rename = "WeightedOnBasePercentage")]
    pub weighted_on_base_percentage: Option<f64>,
    #[serde(rename = "PitchingSingles")]
    pub pitching_singles: Option<f64>,
    #[serde(rename = "PitchingDoubles")]
    pub pitching_doubles: Option<f64>,
    #[serde(rename = "PitchingTriples")]
    pub pitching_triples: Option<f64>,
    #[serde(rename = "PitchingGrandSlams")]
    pub pitching_grand_slams: Option<f64>,
    #[serde(rename = "PitchingHitByPitch")]
    pub pitching_hit_by_pitch: Option<f64>,
    #[serde(rename = "PitchingSacrifices")]
    pub pitching_sacrifices: Option<f64>,
    #[serde(rename = "PitchingSacrificeFlies")]
    pub pitching_sacrifice_flies: Option<f64>,
    #[serde(rename = "PitchingGroundIntoDoublePlay")]
    pub pitching_ground_into_double_play: Option<f64>,
    #[serde(rename = "PitchingCompleteGames")]
    pub pitching_complete_games: Option<f64>,
    #[serde(rename = "PitchingShutOuts")]
    pub pitching_shut_outs: Option<f64>,
    #[serde(rename = "PitchingNoHitters")]
    pub pitching_no_hitters: Option<f64>,
    #[serde(rename = "PitchingPerfectGames")]
    pub pitching_perfect_games: Option<f64>,
    #[serde(rename = "PitchingPlateAppearances")]
    pub pitching_plate_appearances: Option<f64>,
    #[serde(rename = "PitchingTotalBases")]
    pub pitching_total_bases: Option<f64>,
    #[serde(rename = "PitchingFlyOuts")]
    pub pitching_fly_outs: Option<f64>,
    #[serde(rename = "PitchingGroundOuts")]
    pub pitching_ground_outs: Option<f64>,
    #[serde(rename = "PitchingLineOuts")]
    pub pitching_line_outs: Option<f64>,
    #[serde(rename = "PitchingPopOuts")]
    pub pitching_pop_outs: Option<f64>,
    #[serde(rename = "PitchingIntentionalWalks")]
    pub pitching_intentional_walks: Option<f64>,
    #[serde(rename = "PitchingReachedOnError")]
    pub pitching_reached_on_error: Option<f64>,
    #[serde(rename = "PitchingCatchersInterference")]
    pub pitching_catchers_interference: Option<f64>,
    #[serde(rename = "PitchingBallsInPlay")]
    pub pitching_balls_in_play: Option<f64>,
    #[serde(rename = "PitchingOnBasePercentage")]
    pub pitching_on_base_percentage: Option<f64>,
    #[serde(rename = "PitchingSluggingPercentage")]
    pub pitching_slugging_percentage: Option<f64>,
    #[serde(rename = "PitchingOnBasePlusSlugging")]
    pub pitching_on_base_plus_slugging: Option<f64>,
    #[serde(rename = "PitchingStrikeoutsPerNineInnings")]
    pub pitching_strikeouts_per_nine_innings: Option<f64>,
    #[serde(rename = "PitchingWalksPerNineInnings")]
    pub pitching_walks_per_nine_innings: Option<f64>,
    #[serde(rename = "PitchingBattingAverageOnBallsInPlay")]
    pub pitching_batting_average_on_balls_in_play: Option<f64>,
    #[serde(rename = "PitchingWeightedOnBasePercentage")]
    pub pitching_weighted_on_base_percentage: Option<f64>,
    #[serde(rename = "DoublePlays")]
    pub double_plays: Option<f64>,
    #[serde(rename = "PitchingDoublePlays")]
    pub pitching_double_plays: Option<f64>,
    #[serde(rename = "BattingOrderConfirmed")]
    pub batting_order_confirmed: Option<bool>,
    #[serde(rename = "IsolatedPower")]
    pub isolated_power: Option<f64>,
    #[serde(rename = "FieldingIndependentPitching")]
    pub fielding_independent_pitching: Option<f64>,
    #[serde(rename = "PitchingQualityStarts")]
    pub pitching_quality_starts: Option<f64>,
    #[serde(rename = "PitchingInningStarted")]
    pub pitching_inning_started: Option<i32>,
    #[serde(rename = "LeftOnBase")]
    pub left_on_base: Option<f64>,
    #[serde(rename = "PitchingHolds")]
    pub pitching_holds: Option<f64>,
    #[serde(rename = "PitchingBlownSaves")]
    pub pitching_blown_saves: Option<f64>,
    #[serde(rename = "SubstituteBattingOrder")]
    pub substitute_batting_order: Option<i32>,
    #[serde(rename = "SubstituteBattingOrderSequence")]
    pub substitute_batting_order_sequence: Option<i32>,
    #[serde(rename = "FantasyPointsFantasyDraft")]
    pub fantasy_points_fantasy_draft: Option<f64>,
    #[serde(rename = "FantasyPointsBatting")]
    pub fantasy_points_batting: Option<f64>,
    #[serde(rename = "FantasyPointsPitching")]
    pub fantasy_points_pitching: Option<f64>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PlayerGame {
    #[serde(rename = "StatID")]
    pub stat_id: i64,
    #[serde(rename = "TeamID")]
    pub team_id: Option<i32>,
    #[serde(rename = "PlayerID")]
    pub player_id: i64,
    #[serde(rename = "SeasonType")]
    pub season_type: Option<i32>,
    #[serde(rename = "Season")]
    pub season: Option<i32>,
    #[serde(rename = "Name")]
    pub name: Option<String>,
    #[serde(rename = "Team")]
    pub team: Option<String>,
    #[serde(rename = "Position")]
    pub position: Option<String>,
    #[serde(rename = "PositionCategory")]
    pub position_category: Option<String>,
    #[serde(rename = "Started")]
    pub started: Option<i32>,
    #[serde(rename = "BattingOrder")]
    pub batting_order: Option<i32>,
    #[serde(rename = "FanDuelSalary")]
    pub fan_duel_salary: Option<i32>,
    #[serde(rename = "DraftKingsSalary")]
    pub draft_kings_salary: Option<i32>,
    #[serde(rename = "FantasyDataSalary")]
    pub fantasy_data_salary: Option<i32>,
    #[serde(rename = "YahooSalary")]
    pub yahoo_salary: Option<i32>,
    #[serde(rename = "InjuryStatus")]
    pub injury_status: Option<String>,
    #[serde(rename = "InjuryBodyPart")]
    pub injury_body_part: Option<String>,
    #[serde(rename = "InjuryStartDate")]
    pub injury_start_date: Option<String>,
    #[serde(rename = "InjuryNotes")]
    pub injury_notes: Option<String>,
    #[serde(rename = "FanDuelPosition")]
    pub fan_duel_position: Option<String>,
    #[serde(rename = "DraftKingsPosition")]
    pub draft_kings_position: Option<String>,
    #[serde(rename = "YahooPosition")]
    pub yahoo_position: Option<String>,
    #[serde(rename = "OpponentRank")]
    pub opponent_rank: Option<i32>,
    #[serde(rename = "OpponentPositionRank")]
    pub opponent_position_rank: Option<i32>,
    #[serde(rename = "GlobalTeamID")]
    pub global_team_id: i64,
    #[serde(rename = "FantasyDraftSalary")]
    pub fantasy_draft_salary: Option<i32>,
    #[serde(rename = "FantasyDraftPosition")]
    pub fantasy_draft_position: Option<String>,
    #[serde(rename = "GameID")]
    pub game_id: i64,
    #[serde(rename = "OpponentID")]
    pub opponent_id: Option<i32>,
    #[serde(rename = "Opponent")]
    pub opponent: String,
    #[serde(rename = "Day")]
    pub day: String,
    #[serde(rename = "DateTime")]
    pub date_time: String,
    #[serde(rename = "HomeOrAway")]
    pub home_or_away: String,
    #[serde(rename = "IsGameOver")]
    pub is_game_over: Option<bool>,
    #[serde(rename = "GlobalGameID")]
    pub global_game_id: i64,
    #[serde(rename = "GlobalOpponentID")]
    pub global_opponent_id: i64,
    #[serde(rename = "Updated")]
    pub updated: String,
    #[serde(rename = "Games")]
    pub games: Option<f64>,
    #[serde(rename = "FantasyPoints")]
    pub fantasy_points: Option<f64>,
    #[serde(rename = "AtBats")]
    pub at_bats: Option<f64>,
    #[serde(rename = "Runs")]
    pub runs: Option<f64>,
    #[serde(rename = "Hits")]
    pub hits: Option<f64>,
    #[serde(rename = "Singles")]
    pub singles: Option<f64>,
    #[serde(rename = "Doubles")]
    pub doubles: Option<f64>,
    #[serde(rename = "Triples")]
    pub triples: Option<f64>,
    #[serde(rename = "HomeRuns")]
    pub home_runs: Option<f64>,
    #[serde(rename = "RunsBattedIn")]
    pub runs_batted_in: Option<f64>,
    #[serde(rename = "BattingAverage")]
    pub batting_average: Option<f64>,
    #[serde(rename = "Outs")]
    pub outs: Option<f64>,
    #[serde(rename = "Strikeouts")]
    pub strikeouts: Option<f64>,
    #[serde(rename = "Walks")]
    pub walks: Option<f64>,
    #[serde(rename = "HitByPitch")]
    pub hit_by_pitch: Option<f64>,
    #[serde(rename = "Sacrifices")]
    pub sacrifices: Option<f64>,
    #[serde(rename = "SacrificeFlies")]
    pub sacrifice_flies: Option<f64>,
    #[serde(rename = "GroundIntoDoublePlay")]
    pub ground_into_double_play: Option<f64>,
    #[serde(rename = "StolenBases")]
    pub stolen_bases: Option<f64>,
    #[serde(rename = "CaughtStealing")]
    pub caught_stealing: Option<f64>,
    #[serde(rename = "PitchesSeen")]
    pub pitches_seen: Option<f64>,
    #[serde(rename = "OnBasePercentage")]
    pub on_base_percentage: Option<f64>,
    #[serde(rename = "SluggingPercentage")]
    pub slugging_percentage: Option<f64>,
    #[serde(rename = "OnBasePlusSlugging")]
    pub on_base_plus_slugging: Option<f64>,
    #[serde(rename = "Errors")]
    pub errors: Option<f64>,
    #[serde(rename = "Wins")]
    pub wins: Option<f64>,
    #[serde(rename = "Losses")]
    pub losses: Option<f64>,
    #[serde(rename = "Saves")]
    pub saves: Option<f64>,
    #[serde(rename = "InningsPitchedDecimal")]
    pub innings_pitched_decimal: Option<f64>,
    #[serde(rename = "TotalOutsPitched")]
    pub total_outs_pitched: Option<f64>,
    #[serde(rename = "InningsPitchedFull")]
    pub innings_pitched_full: Option<f64>,
    #[serde(rename = "InningsPitchedOuts")]
    pub innings_pitched_outs: Option<f64>,
    #[serde(rename = "EarnedRunAverage")]
    pub earned_run_average: Option<f64>,
    #[serde(rename = "PitchingHits")]
    pub pitching_hits: Option<f64>,
    #[serde(rename = "PitchingRuns")]
    pub pitching_runs: Option<f64>,
    #[serde(rename = "PitchingEarnedRuns")]
    pub pitching_earned_runs: Option<f64>,
    #[serde(rename = "PitchingWalks")]
    pub pitching_walks: Option<f64>,
    #[serde(rename = "PitchingStrikeouts")]
    pub pitching_strikeouts: Option<f64>,
    #[serde(rename = "PitchingHomeRuns")]
    pub pitching_home_runs: Option<f64>,
    #[serde(rename = "PitchesThrown")]
    pub pitches_thrown: Option<f64>,
    #[serde(rename = "PitchesThrownStrikes")]
    pub pitches_thrown_strikes: Option<f64>,
    #[serde(rename = "WalksHitsPerInningsPitched")]
    pub walks_hits_per_innings_pitched: Option<f64>,
    #[serde(rename = "PitchingBattingAverageAgainst")]
    pub pitching_batting_average_against: Option<f64>,
    #[serde(rename = "GrandSlams")]
    pub grand_slams: Option<f64>,
    #[serde(rename = "FantasyPointsFanDuel")]
    pub fantasy_points_fan_duel: Option<f64>,
    #[serde(rename = "FantasyPointsDraftKings")]
    pub fantasy_points_draft_kings: Option<f64>,
    #[serde(rename = "FantasyPointsYahoo")]
    pub fantasy_points_yahoo: Option<f64>,
    #[serde(rename = "PlateAppearances")]
    pub plate_appearances: Option<f64>,
    #[serde(rename = "TotalBases")]
    pub total_bases: Option<f64>,
    #[serde(rename = "FlyOuts")]
    pub fly_outs: Option<f64>,
    #[serde(rename = "GroundOuts")]
    pub ground_outs: Option<f64>,
    #[serde(rename = "LineOuts")]
    pub line_outs: Option<f64>,
    #[serde(rename = "PopOuts")]
    pub pop_outs: Option<f64>,
    #[serde(rename = "IntentionalWalks")]
    pub intentional_walks: Option<f64>,
    #[serde(rename = "ReachedOnError")]
    pub reached_on_error: Option<f64>,
    #[serde(rename = "BallsInPlay")]
    pub balls_in_play: Option<f64>,
    #[serde(rename = "BattingAverageOnBallsInPlay")]
    pub batting_average_on_balls_in_play: Option<f64>,
    #[serde(rename = "WeightedOnBasePercentage")]
    pub weighted_on_base_percentage: Option<f64>,
    #[serde(rename = "PitchingSingles")]
    pub pitching_singles: Option<f64>,
    #[serde(rename = "PitchingDoubles")]
    pub pitching_doubles: Option<f64>,
    #[serde(rename = "PitchingTriples")]
    pub pitching_triples: Option<f64>,
    #[serde(rename = "PitchingGrandSlams")]
    pub pitching_grand_slams: Option<f64>,
    #[serde(rename = "PitchingHitByPitch")]
    pub pitching_hit_by_pitch: Option<f64>,
    #[serde(rename = "PitchingSacrifices")]
    pub pitching_sacrifices: Option<f64>,
    #[serde(rename = "PitchingSacrificeFlies")]
    pub pitching_sacrifice_flies: Option<f64>,
    #[serde(rename = "PitchingGroundIntoDoublePlay")]
    pub pitching_ground_into_double_play: Option<f64>,
    #[serde(rename = "PitchingCompleteGames")]
    pub pitching_complete_games: Option<f64>,
    #[serde(rename = "PitchingShutOuts")]
    pub pitching_shut_outs: Option<f64>,
    #[serde(rename = "PitchingNoHitters")]
    pub pitching_no_hitters: Option<f64>,
    #[serde(rename = "PitchingPerfectGames")]
    pub pitching_perfect_games: Option<f64>,
    #[serde(rename = "PitchingPlateAppearances")]
    pub pitching_plate_appearances: Option<f64>,
    #[serde(rename = "PitchingTotalBases")]
    pub pitching_total_bases: Option<f64>,
    #[serde(rename = "PitchingFlyOuts")]
    pub pitching_fly_outs: Option<f64>,
    #[serde(rename = "PitchingGroundOuts")]
    pub pitching_ground_outs: Option<f64>,
    #[serde(rename = "PitchingLineOuts")]
    pub pitching_line_outs: Option<f64>,
    #[serde(rename = "PitchingPopOuts")]
    pub pitching_pop_outs: Option<f64>,
    #[serde(rename = "PitchingIntentionalWalks")]
    pub pitching_intentional_walks: Option<f64>,
    #[serde(rename = "PitchingReachedOnError")]
    pub pitching_reached_on_error: Option<f64>,
    #[serde(rename = "PitchingCatchersInterference")]
    pub pitching_catchers_interference: Option<f64>,
    #[serde(rename = "PitchingBallsInPlay")]
    pub pitching_balls_in_play: Option<f64>,
    #[serde(rename = "PitchingOnBasePercentage")]
    pub pitching_on_base_percentage: Option<f64>,
    #[serde(rename = "PitchingSluggingPercentage")]
    pub pitching_slugging_percentage: Option<f64>,
    #[serde(rename = "PitchingOnBasePlusSlugging")]
    pub pitching_on_base_plus_slugging: Option<f64>,
    #[serde(rename = "PitchingStrikeoutsPerNineInnings")]
    pub pitching_strikeouts_per_nine_innings: Option<f64>,
    #[serde(rename = "PitchingWalksPerNineInnings")]
    pub pitching_walks_per_nine_innings: Option<f64>,
    #[serde(rename = "PitchingBattingAverageOnBallsInPlay")]
    pub pitching_batting_average_on_balls_in_play: Option<f64>,
    #[serde(rename = "PitchingWeightedOnBasePercentage")]
    pub pitching_weighted_on_base_percentage: Option<f64>,
    #[serde(rename = "DoublePlays")]
    pub double_plays: Option<f64>,
    #[serde(rename = "PitchingDoublePlays")]
    pub pitching_double_plays: Option<f64>,
    #[serde(rename = "BattingOrderConfirmed")]
    pub batting_order_confirmed: Option<bool>,
    #[serde(rename = "IsolatedPower")]
    pub isolated_power: Option<f64>,
    #[serde(rename = "FieldingIndependentPitching")]
    pub fielding_independent_pitching: Option<f64>,
    #[serde(rename = "PitchingQualityStarts")]
    pub pitching_quality_starts: Option<f64>,
    #[serde(rename = "PitchingInningStarted")]
    pub pitching_inning_started: Option<i32>,
    #[serde(rename = "LeftOnBase")]
    pub left_on_base: Option<f64>,
    #[serde(rename = "PitchingHolds")]
    pub pitching_holds: Option<f64>,
    #[serde(rename = "PitchingBlownSaves")]
    pub pitching_blown_saves: Option<f64>,
    #[serde(rename = "SubstituteBattingOrder")]
    pub substitute_batting_order: Option<i32>,
    #[serde(rename = "SubstituteBattingOrderSequence")]
    pub substitute_batting_order_sequence: Option<i32>,
    #[serde(rename = "FantasyPointsFantasyDraft")]
    pub fantasy_points_fantasy_draft: Option<f64>,
    #[serde(rename = "FantasyPointsBatting")]
    pub fantasy_points_batting: Option<f64>,
    #[serde(rename = "FantasyPointsPitching")]
    pub fantasy_points_pitching: Option<f64>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct BoxScore {
    #[serde(rename = "Game")]
    pub game: Game,
    #[serde(rename = "Innings")]
    pub innings: Vec<Inning>,
    #[serde(rename = "TeamGames")]
    pub team_games: Vec<TeamGame>,
    #[serde(rename = "PlayerGames")]
    pub player_games: Vec<PlayerGame>,
}

// BoxScoreResponse removed - use BoxScore directly
