use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Inning {
    #[serde(rename = "InningID")]
    pub inning_id: i64,
    #[serde(rename = "GameID")]
    pub game_id: i64,
    #[serde(rename = "InningNumber")]
    pub inning_number: i32,
    #[serde(rename = "AwayTeamRuns")]
    pub away_team_runs: i32,
    #[serde(rename = "HomeTeamRuns")]
    pub home_team_runs: i32,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SeriesInfo {
    #[serde(rename = "HomeTeamWins")]
    pub home_team_wins: i32,
    #[serde(rename = "AwayTeamWins")]
    pub away_team_wins: i32,
    #[serde(rename = "GameNumber")]
    pub game_number: i32,
    #[serde(rename = "MaxLength")]
    pub max_length: i32,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct GameByDate {
    #[serde(rename = "GameID")]
    pub game_id: i64,
    #[serde(rename = "Season")]
    pub season: i32,
    #[serde(rename = "SeasonType")]
    pub season_type: i32,
    #[serde(rename = "Status")]
    pub status: String,
    #[serde(rename = "Day")]
    pub day: String,
    #[serde(rename = "DateTime")]
    pub date_time: String,
    #[serde(rename = "AwayTeam")]
    pub away_team: String,
    #[serde(rename = "HomeTeam")]
    pub home_team: String,
    #[serde(rename = "AwayTeamID")]
    pub away_team_id: i32,
    #[serde(rename = "HomeTeamID")]
    pub home_team_id: i32,
    #[serde(rename = "StadiumID")]
    pub stadium_id: i32,
    #[serde(rename = "Channel")]
    pub channel: Option<String>,
    #[serde(rename = "Inning")]
    pub inning: Option<i32>,
    #[serde(rename = "InningHalf")]
    pub inning_half: Option<String>,
    #[serde(rename = "AwayTeamRuns")]
    pub away_team_runs: Option<i32>,
    #[serde(rename = "HomeTeamRuns")]
    pub home_team_runs: Option<i32>,
    #[serde(rename = "AwayTeamHits")]
    pub away_team_hits: Option<i32>,
    #[serde(rename = "HomeTeamHits")]
    pub home_team_hits: Option<i32>,
    #[serde(rename = "AwayTeamErrors")]
    pub away_team_errors: Option<i32>,
    #[serde(rename = "HomeTeamErrors")]
    pub home_team_errors: Option<i32>,
    #[serde(rename = "WinningPitcherID")]
    pub winning_pitcher_id: Option<i64>,
    #[serde(rename = "LosingPitcherID")]
    pub losing_pitcher_id: Option<i64>,
    #[serde(rename = "SavingPitcherID")]
    pub saving_pitcher_id: Option<i64>,
    #[serde(rename = "Attendance")]
    pub attendance: Option<i32>,
    #[serde(rename = "AwayTeamProbablePitcherID")]
    pub away_team_probable_pitcher_id: Option<i64>,
    #[serde(rename = "HomeTeamProbablePitcherID")]
    pub home_team_probable_pitcher_id: Option<i64>,
    #[serde(rename = "Outs")]
    pub outs: Option<i32>,
    #[serde(rename = "Balls")]
    pub balls: Option<i32>,
    #[serde(rename = "Strikes")]
    pub strikes: Option<i32>,
    #[serde(rename = "CurrentPitcherID")]
    pub current_pitcher_id: Option<i64>,
    #[serde(rename = "CurrentHitterID")]
    pub current_hitter_id: Option<i64>,
    #[serde(rename = "AwayTeamStartingPitcherID")]
    pub away_team_starting_pitcher_id: Option<i64>,
    #[serde(rename = "HomeTeamStartingPitcherID")]
    pub home_team_starting_pitcher_id: Option<i64>,
    #[serde(rename = "CurrentPitchingTeamID")]
    pub current_pitching_team_id: Option<i32>,
    #[serde(rename = "CurrentHittingTeamID")]
    pub current_hitting_team_id: Option<i32>,
    #[serde(rename = "PointSpread")]
    pub point_spread: Option<f64>,
    #[serde(rename = "OverUnder")]
    pub over_under: Option<f64>,
    #[serde(rename = "AwayTeamMoneyLine")]
    pub away_team_money_line: Option<i32>,
    #[serde(rename = "HomeTeamMoneyLine")]
    pub home_team_money_line: Option<i32>,
    #[serde(rename = "ForecastTempLow")]
    pub forecast_temp_low: Option<i32>,
    #[serde(rename = "ForecastTempHigh")]
    pub forecast_temp_high: Option<i32>,
    #[serde(rename = "ForecastDescription")]
    pub forecast_description: Option<String>,
    #[serde(rename = "ForecastWindChill")]
    pub forecast_wind_chill: Option<i32>,
    #[serde(rename = "ForecastWindSpeed")]
    pub forecast_wind_speed: Option<i32>,
    #[serde(rename = "ForecastWindDirection")]
    pub forecast_wind_direction: Option<i32>,
    #[serde(rename = "RescheduledFromGameID")]
    pub rescheduled_from_game_id: Option<i64>,
    #[serde(rename = "RunnerOnFirst")]
    pub runner_on_first: Option<bool>,
    #[serde(rename = "RunnerOnSecond")]
    pub runner_on_second: Option<bool>,
    #[serde(rename = "RunnerOnThird")]
    pub runner_on_third: Option<bool>,
    #[serde(rename = "AwayTeamStartingPitcher")]
    pub away_team_starting_pitcher: Option<String>,
    #[serde(rename = "HomeTeamStartingPitcher")]
    pub home_team_starting_pitcher: Option<String>,
    #[serde(rename = "CurrentPitcher")]
    pub current_pitcher: Option<String>,
    #[serde(rename = "CurrentHitter")]
    pub current_hitter: Option<String>,
    #[serde(rename = "WinningPitcher")]
    pub winning_pitcher: Option<String>,
    #[serde(rename = "LosingPitcher")]
    pub losing_pitcher: Option<String>,
    #[serde(rename = "SavingPitcher")]
    pub saving_pitcher: Option<String>,
    #[serde(rename = "DueUpHitterID1")]
    pub due_up_hitter_id1: Option<i64>,
    #[serde(rename = "DueUpHitterID2")]
    pub due_up_hitter_id2: Option<i64>,
    #[serde(rename = "DueUpHitterID3")]
    pub due_up_hitter_id3: Option<i64>,
    #[serde(rename = "GlobalGameID")]
    pub global_game_id: i64,
    #[serde(rename = "GlobalAwayTeamID")]
    pub global_away_team_id: i64,
    #[serde(rename = "GlobalHomeTeamID")]
    pub global_home_team_id: i64,
    #[serde(rename = "PointSpreadAwayTeamMoneyLine")]
    pub point_spread_away_team_money_line: Option<i32>,
    #[serde(rename = "PointSpreadHomeTeamMoneyLine")]
    pub point_spread_home_team_money_line: Option<i32>,
    #[serde(rename = "LastPlay")]
    pub last_play: Option<String>,
    #[serde(rename = "IsClosed")]
    pub is_closed: bool,
    #[serde(rename = "Updated")]
    pub updated: String,
    #[serde(rename = "GameEndDateTime")]
    pub game_end_date_time: Option<String>,
    #[serde(rename = "HomeRotationNumber")]
    pub home_rotation_number: i32,
    #[serde(rename = "AwayRotationNumber")]
    pub away_rotation_number: i32,
    #[serde(rename = "NeutralVenue")]
    pub neutral_venue: bool,
    #[serde(rename = "InningDescription")]
    pub inning_description: Option<String>,
    #[serde(rename = "OverPayout")]
    pub over_payout: Option<i32>,
    #[serde(rename = "UnderPayout")]
    pub under_payout: Option<i32>,
    #[serde(rename = "DateTimeUTC")]
    pub date_time_utc: String,
    #[serde(rename = "HomeTeamOpener")]
    pub home_team_opener: Option<bool>,
    #[serde(rename = "AwayTeamOpener")]
    pub away_team_opener: Option<bool>,
    #[serde(rename = "SuspensionResumeDay")]
    pub suspension_resume_day: Option<String>,
    #[serde(rename = "SuspensionResumeDateTime")]
    pub suspension_resume_date_time: Option<String>,
    #[serde(rename = "SeriesInfo")]
    pub series_info: SeriesInfo,
    #[serde(rename = "Innings")]
    pub innings: Vec<Inning>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct GameByDateResponse {
    pub data: Option<GameByDate>,
    pub date: String,
    pub game_id: i64,
    pub league: String,
}
